### ISSUE TITLE
AVTransportException: Not enough IN args, too many IN args, no IN arg by that name, one or more IN args are of the wrong data type. Invalid DIDL metadata: org.seamless.xml.ParserException: java.lang.NullPointerException.

### ISSUE THREAD

**Issue by pataquets** [haku/toadcast#2]
Running a Docker container (as it is in #1) like this:
```
$ docker run --rm -it --net=host pataquets/toadcast --displayname ToadCast --chromecast Dormitori
```

Boots OK, AFAICT:
```
 22:59:26.247 [      main] c.vaguehope.toadcast.Main I interfaces: [/172.17.0.1, /192.168.1.20], using interface: /172.17.0.1
 22:59:26.300 [      main] c.vaguehope.toadcast.Main I hostName: [REDACTED]
 22:59:26.495 [      main] c.vaguehope.toadcast.Main I uniqueSystemIdentifier: uuid:e73304d2-af55-cf03-ffff-ffff9837f134
 22:59:26.720 [      main] o.f.cling.UpnpServiceImpl I >>> Starting UPnP service...
 22:59:26.721 [      main] o.f.cling.UpnpServiceImpl I Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
 22:59:26.853 [      main]    o.f.c.transport.Router I Creating Router: org.fourthline.cling.transport.RouterImpl
 22:59:26.905 [      main] f.c.t.s.MulticastReceiver I Creating wildcard socket (for receiving multicast datagrams) on port: 1900
 22:59:26.960 [      main] f.c.t.s.MulticastReceiver I Joining multicast group: /239.255.255.250:1900 on network interface: enp2s0
 22:59:27.231 [      main]  o.f.c.t.spi.StreamServer I Created server (for receiving TCP streams) on: /192.168.1.20:44731
 22:59:27.235 [      main]    o.f.c.t.spi.DatagramIO I Creating bound socket (for datagram input/output) on: /192.168.1.20
 22:59:27.324 [      main] o.f.cling.UpnpServiceImpl I <<< UPnP service started successfully
 22:59:29.080 [      main]   c.v.toadcast.CastFinder I Watching for ChromeCast Dormitori ...
 22:59:30.515 [  cling-13]   c.v.toadcast.CastFinder I ChromeCast found via UPnP: Dormitori principal (192.168.1.47:8009)
 22:59:33.831 [2-thread-1]   c.v.toadcast.GoalSeeker I Connected to ChromeCast 192.168.1.47.
 22:59:34.169 [  Thread-6]      s.l.c.api.v2.Channel W Error while reading: Unrecognized field "iconUrl" (Class su.litvak.chromecast.api.v2.Application), not marked as ignorable
  at [Source: java.io.StringReader@7862e19; line: 1, column: 615] (through reference chain: su.litvak.chromecast.api.v2.Application["iconUrl"])
 22:59:34.170 [  Thread-6]      s.l.c.api.v2.Channel W  <-- {"requestId":1,"status":{"applications":[{"appId":"E8C28D3C","displayName":"Backdrop","iconUrl":"","isIdleScreen":true,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.sse"},{"name":"urn:x-cast:com.google.cast.remotecontrol"}],"sessionId":"968c5538-fd1c-4a05-a5c2-778298efb40d","statusText":"","transportId":"968c5538-fd1c-4a05-a5c2-778298efb40d"}],"userEq":{},"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}
```

But when sending a Big Buck Bunny video to ToadCast, outputs this:
```
 23:00:56.019 [   cling-7] .v.t.MyAVTransportService I stop(0)
 23:00:56.039 [   cling-7] .v.t.MyAVTransportService I setAVTransportURI(0, http://192.168.1.20:8200/MediaItems/29.mp4, [42])
 23:00:56.047 [   cling-7] c.v.toadcast.UpnpRenderer W Action failed: Action invocation: (Action, Arguments: 3) SetAVTransportURI
 org.fourthline.cling.support.avtransport.AVTransportException: Not enough IN args, too many IN args, no IN arg by that name, one or more IN args are of the wrong data type. Invalid DIDL metadata: org.seamless.xml.ParserException: java.lang.NullPointerException.
 	at com.vaguehope.toadcast.MyAVTransportService.setAVTransportURI(MyAVTransportService.java:79) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
 	at org.seamless.util.Reflections.invoke(Reflections.java:41) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.model.action.MethodActionExecutor.execute(MethodActionExecutor.java:72) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.model.action.AbstractActionExecutor$1.execute(AbstractActionExecutor.java:73) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.model.DefaultServiceManager.execute(DefaultServiceManager.java:128) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at com.vaguehope.toadcast.UpnpRenderer$1.execute(UpnpRenderer.java:57) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.model.action.AbstractActionExecutor.execute(AbstractActionExecutor.java:71) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.protocol.sync.ReceivingAction.executeSync(ReceivingAction.java:104) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.protocol.ReceivingSync.execute(ReceivingSync.java:63) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.protocol.ReceivingAsync.run(ReceivingAsync.java:71) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.transport.spi.UpnpStream.process(UpnpStream.java:82) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at org.fourthline.cling.transport.impl.HttpExchangeUpnpStream.run(HttpExchangeUpnpStream.java:119) ~[toadcast-1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
 	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
I have no clue on what's going on. Help much appreciated.

**Comment by haku** [comment]
From the stack trace it sounds like the DIDL document supplied is wrong in some way, or at least is missing something the library wants.  I suggest changing MyAVTransportService.java line 79 to be:

```
throw new AVTransportException(ErrorCode.INVALID_ARGS, "Invalid DIDL metadata: ", e);
```

So that you get the full stack trace and can debug from there.

Does it do this when not built/run using Docker?
